version: '2'
services:
  backend:
    build: ../salonfinder-server
    ports:
      - "3000:3000"
  frontend:
    build: ./
    ports:
      - "80:4200"
  database:
    image: "mongo"
    ports:
      - "27017:27017"